const express=require("express")
const app=express()
const cookieParser=require('cookie-parser')
app.use(cookieParser())
app.set('view engine','ejs')
app.set('views',__dirname+'/app/views')
app.use(express.static(__dirname+'/app/libs'))
app.use(require(__dirname+'/app/routes/admin_routing'))
app.use(require(__dirname+'/app/routes/category_routing'))
app.use(require(__dirname+'/app/routes/coustmer_routing'))
app.use(require(__dirname+'/app/routes/product_routing'))
app.use(require(__dirname+'/app/routes/test_routing'))
app.listen(3000)